# Generated by Django 5.2.15 on 2026-06-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profiles/default.png", upload_to="profiles/"
            ),
        ),
    ]
