# Generated by Django 5.2.15 on 2026-06-12 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campeonato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("temporada", models.IntegerField()),
                (
                    "premiacao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("rodada_atual", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="Grupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=5)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campeonatos.campeonato",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("bandeira", models.ImageField(upload_to="bandeiras/")),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="campeonatos.grupo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rodada", models.IntegerField()),
                ("data_jogo", models.DateTimeField()),
                ("gols_casa", models.IntegerField(blank=True, null=True)),
                ("gols_visitante", models.IntegerField(blank=True, null=True)),
                ("encerrado", models.BooleanField(default=False)),
                (
                    "campeonato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campeonatos.campeonato",
                    ),
                ),
                (
                    "time_casa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casa",
                        to="campeonatos.time",
                    ),
                ),
                (
                    "time_visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitante",
                        to="campeonatos.time",
                    ),
                ),
            ],
        ),
    ]
