# Generated by Django 5.2.15 on 2026-06-12 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campeonatos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="campeonato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grupos",
                to="campeonatos.campeonato",
            ),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="campeonato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jogos",
                to="campeonatos.campeonato",
            ),
        ),
        migrations.AlterField(
            model_name="time",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="times",
                to="campeonatos.grupo",
            ),
        ),
        migrations.CreateModel(
            name="Palpite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gols_casa", models.PositiveIntegerField()),
                ("gols_visitante", models.PositiveIntegerField()),
                ("pontos", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "jogo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="palpites",
                        to="campeonatos.jogo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="palpites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "jogo")},
            },
        ),
    ]
