# Generated by Django 5.2.15 on 2026-06-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campeonatos", "0002_alter_grupo_campeonato_alter_jogo_campeonato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogo",
            name="estadio",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
