# Generated by Django 5.2.15 on 2026-06-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campeonatos", "0003_jogo_estadio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grupo",
            name="nome",
            field=models.CharField(max_length=7),
        ),
    ]
