# Generated by Django 5.2.15 on 2026-06-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campeonatos", "0005_perfil"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palpite",
            name="gols_casa",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="palpite",
            name="gols_visitante",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
