# Generated by Django 5.2.15 on 2026-06-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campeonatos", "0006_alter_palpite_gols_casa_alter_palpite_gols_visitante"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="time",
            name="bandeira",
        ),
        migrations.AddField(
            model_name="time",
            name="codigo_pais",
            field=models.CharField(default="br", max_length=2),
        ),
    ]
