# Generated by Django 5.2.15 on 2026-06-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campeonatos", "0007_remove_time_bandeira_time_codigo_pais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="codigo_pais",
            field=models.CharField(max_length=2),
        ),
    ]
