# Generated by Django 5.2.15 on 2026-06-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campeonatos", "0008_alter_time_codigo_pais"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogo",
            name="pontos_calculados",
            field=models.BooleanField(default=False),
        ),
    ]
