# Generated by Django 5.2.15 on 2026-06-14 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campeonatos", "0009_jogo_pontos_calculados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogo",
            name="time_casa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jogos_casa",
                to="campeonatos.time",
            ),
        ),
        migrations.AlterField(
            model_name="jogo",
            name="time_visitante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jogos_visitante",
                to="campeonatos.time",
            ),
        ),
        migrations.DeleteModel(
            name="Perfil",
        ),
    ]
