# Generated by Django 5.2.15 on 2026-06-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campeonatos", "0010_alter_jogo_time_casa_alter_jogo_time_visitante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogo",
            name="codigo_jogo",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
